server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mybatis
    userName: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  mapper-locations: classpath:com/xbsj/mapper/*.xml
  config-location: classpath:mybatis.xml
  type-aliases-package: com.xbsj.entity

